name: Test on PR

on: 
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test infra on PR
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info


    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd infrastructure
        $COMMAND_IAC init -reconfigure
        $COMMAND_IAC validate
        $COMMAND_IAC plan